//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jazz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public System.DateTime DateTimeOfAppointment { get; set; }
        public int ServiceId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Student Student { get; set; }
        public virtual User User { get; set; }
    }
}
